# Generated by Django 6.0.3 on 2026-03-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Общий опыт (XP)'),
        ),
    ]
