# Generated by Django 6.0.3 on 2026-03-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_future_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Курс / Класс'),
        ),
        migrations.AddField(
            model_name='user',
            name='educational_institution',
            field=models.CharField(blank=True, help_text='Например: МГТУ им. Баумана или Школа №123', max_length=255, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
