# Generated by Django 6.0.3 on 2026-03-27 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_course_user_educational_institution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название аватарки')),
                ('image', models.ImageField(upload_to='avatars/', verbose_name='Изображение аватарки')),
                ('is_selectable', models.BooleanField(default=True, verbose_name='Доступна для выбора')),
            ],
            options={
                'verbose_name': 'Аватарка',
                'verbose_name_plural': 'Аватарки',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.avatar', verbose_name='Аватарка'),
        ),
    ]
