# Generated by Django 4.2.16 on 2026-04-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_specialty_alter_user_course_user_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='future_profession',
            field=models.CharField(blank=True, help_text='Например: Data Scientist', max_length=255, null=True, verbose_name='Желаемая профессия'),
        ),
    ]
