# Generated by Django 4.2.11 on 2026-04-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_avatar_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='future_profession',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
