# Generated by Django 4.2.16 on 2026-05-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, default='', help_text='Название компании работодателя', max_length=255, verbose_name='Организация'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('role', 'EMPLOYER'), _negated=True), ('organization__gt', ''), _connector='OR'), name='employer_must_have_organization'),
        ),
    ]
