# Generated by Django 4.2.16 on 2026-06-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_studentfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Город проживания (обязательно для студентов и школьников)', max_length=100, verbose_name='Город'),
        ),
    ]
