# Generated by Django 4.2.16 on 2026-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Дата рождения (только для студентов и школьников)', null=True, verbose_name='Дата рождения'),
        ),
    ]
