# Generated by Django 4.2.16 on 2026-04-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название мероприятия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('OLYMPIAD', 'Олимпиада'), ('HACKATHON', 'Хакатон'), ('COMPETITION', 'Конкурс'), ('CONFERENCE', 'Конференция'), ('GRANT', 'Грант')], default='OLYMPIAD', max_length=20, verbose_name='Тип мероприятия')),
                ('source', models.CharField(choices=[('URFU_IZUMRUD', 'УрФУ «Изумруд»'), ('URFU_VUZAKADEM', 'УрФУ Вузовско-академическая'), ('MIPT', 'МФТИ'), ('BMSTU', 'МГТУ им. Баумана'), ('ITMO', 'ИТМО'), ('VSOSH', 'ВСОШ'), ('MANUAL', 'Добавлено вручную')], max_length=20, verbose_name='Источник')),
                ('source_url', models.URLField(help_text='Ссылка на страницу результатов', max_length=1000, verbose_name='URL на источнике')),
                ('participant_name', models.CharField(max_length=255, verbose_name='ФИО участника')),
                ('result_status', models.CharField(choices=[('WINNER', 'Победитель'), ('PRIZE', 'Призёр'), ('PARTICIPANT', 'Участник'), ('UNKNOWN', 'Не указано')], default='UNKNOWN', max_length=20, verbose_name='Результат')),
                ('subject_area', models.CharField(blank=True, help_text='Например: Информатика, Математика, Физика', max_length=255, verbose_name='Предметная область / Профиль')),
                ('region', models.CharField(blank=True, help_text='Город участника, если известен', max_length=255, verbose_name='Регион / Город')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='Класс / Курс')),
                ('year', models.CharField(blank=True, help_text='Например: 2025/26', max_length=20, verbose_name='Учебный год')),
                ('organizer', models.CharField(blank=True, max_length=500, verbose_name='Организатор')),
                ('score', models.CharField(blank=True, max_length=50, verbose_name='Балл')),
                ('place', models.CharField(blank=True, max_length=50, verbose_name='Место')),
                ('venue', models.CharField(blank=True, max_length=255, verbose_name='Площадка')),
                ('keywords', models.TextField(blank=True, help_text='Через запятую, для ИИ-рекомендаций', verbose_name='Ключевые слова')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('parsed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата парсинга')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-parsed_at'],
                'unique_together': {('source', 'participant_name', 'subject_area', 'year')},
            },
        ),
    ]
