# Generated by Django 4.2.16 on 2026-04-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='event',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Для какого класса / курса'),
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, max_length=255, verbose_name='Регион / Город проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('URFU_IZUMRUD', 'УрФУ «Изумруд»'), ('URFU_VUZAKADEM', 'УрФУ Вузовско-академическая'), ('MIPT', 'МФТИ'), ('BMSTU', 'МГТУ им. Баумана'), ('ITMO', 'ИТМО'), ('VSOSH', 'ВСОШ'), ('MANUAL', 'Добавлено вручную')], max_length=20, verbose_name='Источник (с какого сайта спарсено)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='source_url',
            field=models.URLField(help_text='Ссылка на страницу мероприятия (используется для дедупликации)', max_length=1000, unique=True, verbose_name='URL на источнике'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participant_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='result_status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='score',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
    ]
