# Generated by Django 4.2.16 on 2026-06-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_unique_together_alter_event_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('URFU_IZUMRUD', 'УрФУ «Изумруд»'), ('URFU_VUZAKADEM', 'УрФУ Вузовско-академическая'), ('MIPT', 'МФТИ'), ('BMSTU', 'МГТУ им. Баумана'), ('ITMO', 'ИТМО'), ('VSOSH', 'ВСОШ'), ('OLIMPIADA_RU', 'Олимпиада.ру'), ('HSE_OLYMP', 'ВШЭ Олимпиады'), ('HACKLIST', 'Hacklist (хакатоны)'), ('POSTUPI_ONLINE', 'Поступи Онлайн'), ('MANUAL', 'Добавлено вручную')], max_length=20, verbose_name='Источник (с какого сайта спарсено)'),
        ),
    ]
