# Generated by Django 4.2.16 on 2026-06-01 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_event_source_add_new_parsers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.CreateModel(
            name='EventTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отслеживание мероприятия',
                'verbose_name_plural': 'Отслеживания мероприятий',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
