# Generated by Django 4.2.16 on 2026-06-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_date_eventtracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('OLYMPIAD', '🧠 Олимпиада'), ('HACKATHON', '💻 Хакатон'), ('COMPETITION', '🏆 Конкурс'), ('CONFERENCE', '🎓 Конференция'), ('GRANT', '💰 Грант')], default='OLYMPIAD', max_length=20, verbose_name='Тип мероприятия'),
        ),
    ]
