# Generated by Django 6.0.3 on 2026-03-26 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('HACKATHON', 'Хакатоны'), ('OLYMPIAD', 'Олимпиады'), ('COURSE', 'Курсы'), ('VOLUNTEER', 'Волонтерство'), ('PUBLICATION', 'Публикации')], max_length=20, verbose_name='Тип')),
                ('date', models.DateField(verbose_name='Дата получения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('organization', models.CharField(max_length=255, verbose_name='Организация')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('status', models.CharField(choices=[('PENDING', 'На проверке'), ('VERIFIED', 'Верифицировано'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата верификации')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AchievementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='achievements/documents/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gamification.achievement')),
            ],
            options={
                'verbose_name': 'Документ достижения',
                'verbose_name_plural': 'Документы достижений',
            },
        ),
    ]
