# Generated by Django 4.2.16 on 2026-04-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OLYMPIAD', '🧠 Олимпиада'), ('HACKATHON', '💻 Проект / Хакатон'), ('COURSE', '📚 Курс / Обучение'), ('VOLUNTEERING', '🤝 Волонтерство'), ('SCIENCE', '🔬 Научная работа'), ('SPORT_ART', '🏅 Спорт / Творчество')], max_length=20, verbose_name='Тип достижения')),
                ('level_category', models.CharField(help_text='Например: UNIVERSITY, REGIONAL, INTERNAL...', max_length=30, verbose_name='Уровень/Категория')),
                ('achievement_level', models.CharField(blank=True, choices=[('PARTICIPANT', 'Участие'), ('PRIZE', 'Призёр'), ('WINNER', 'Победитель')], default='PARTICIPANT', max_length=20, verbose_name='Результат')),
                ('title', models.CharField(max_length=255, verbose_name='Название достижения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Организация/Учреждение')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('hours_count', models.PositiveIntegerField(blank=True, help_text='Для волонтёрства', null=True, verbose_name='Количество часов')),
                ('has_certificate', models.BooleanField(default=False, help_text='Для курсов', verbose_name='Есть сертификат/диплом')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Баллы за достижение (XP)')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING', 'На проверке'), ('VERIFIED', 'Подтверждено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=10, verbose_name='Статус верификации')),
                ('is_rewarded', models.BooleanField(default=False, verbose_name='Опыт начислен')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время подтверждения')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата мероприятия')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AchievementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='achievements/proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название бейджа')),
                ('description', models.TextField(verbose_name='Описание (за что дается)')),
                ('icon', models.ImageField(upload_to='badges/', verbose_name='Иконка бейджа')),
            ],
            options={
                'verbose_name': 'Бейдж',
                'verbose_name_plural': 'Бейджи',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.badge', verbose_name='Бейдж')),
            ],
            options={
                'verbose_name': 'Бейдж пользователя',
                'verbose_name_plural': 'Бейджи пользователей',
            },
        ),
    ]
