# Generated by Django 6.0.3 on 2026-03-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_achievement_is_rewarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='proof_link',
        ),
        migrations.AddField(
            model_name='achievement',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='proofs/%Y/%m/', verbose_name='Файл подтверждения'),
        ),
    ]
