# Generated by Django 4.2.11 on 2026-04-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skill_id_alter_skillcategory_id_and_more'),
        ('portfolio', '0008_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='has_certificate',
            field=models.BooleanField(default=False, help_text='Для курсов', verbose_name='Есть сертификат/диплом'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='hours_count',
            field=models.PositiveIntegerField(blank=True, help_text='Для волонтёрства', null=True, verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='level_category',
            field=models.CharField(help_text='Например: UNIVERSITY, REGIONAL, INTERNAL...', max_length=30, verbose_name='Уровень/Категория'),
        ),
        migrations.AlterField(
            model_name='event',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skills.skill', verbose_name='Прокачиваемые навыки'),
        ),
    ]
