# Generated by Django 4.2.11 on 2026-04-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_achievement_has_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата мероприятия'),
        ),
    ]
