# Generated by Django 4.2.11 on 2026-04-18 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_achievement_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='proof_file',
        ),
        migrations.CreateModel(
            name='AchievementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='achievements/proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='portfolio.achievement')),
            ],
        ),
    ]
