# Generated by Django 4.2.16 on 2026-04-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название навыка')),
                ('description', models.TextField(blank=True, verbose_name='Описание навыка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория навыка',
                'verbose_name_plural': 'Категории навыков',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название профиля')),
            ],
            options={
                'verbose_name': 'Профиль навыков',
                'verbose_name_plural': 'Профили навыков',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Опыт (XP)')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень навыка')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Компетенция студента',
                'verbose_name_plural': 'Матрица компетенций',
            },
        ),
    ]
