# Generated by Django 6.0.3 on 2026-03-18 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.AddField(
            model_name='achievement',
            name='points',
            field=models.PositiveIntegerField(default=10, verbose_name='Баллы за достижение'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='proof_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на подтверждение (сертификат/пост)'),
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Студенты (Участники команды)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING', 'На проверке'), ('VERIFIED', 'Подтверждено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=10, verbose_name='Статус верификации'),
        ),
    ]
