# Generated by Django 6.0.3 on 2026-03-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_student_achievement_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='proof_link',
            field=models.URLField(verbose_name='Ссылка на подтверждение (сертификат/пост)'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
