# Generated by Django 6.0.3 on 2026-03-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_rewarded',
            field=models.BooleanField(default=False, verbose_name='Опыт начислен'),
        ),
    ]
