# Generated by Django 6.0.3 on 2026-03-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_achievement_proof_link_achievement_proof_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='skills',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='event_type',
            field=models.CharField(choices=[('VOLUNTEERING', 'Волонтерство'), ('HACKATHON', 'Хакатон'), ('COURSE', 'Пройденный курс'), ('OLYMPIAD', 'Олимпиада'), ('PUBLICATION', 'Научная публикация'), ('OTHER', 'Другое')], default='HACKATHON', max_length=20, verbose_name='Тип мероприятия'),
        ),
    ]
