# Generated by Django 6.0.3 on 2026-03-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_achievement_skills_and_more'),
        ('skills', '0003_skillprofile_skillcategory_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='skills',
            field=models.ManyToManyField(related_name='achievements', to='skills.skill', verbose_name='Подтверждаемые навыки'),
        ),
    ]
