# Generated by Django 6.0.4 on 2026-04-14 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_event_created'),
        ('skills', '0003_skillprofile_skillcategory_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-created'], 'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AddField(
            model_name='achievement',
            name='achievement_level',
            field=models.CharField(blank=True, choices=[('PARTICIPANT', 'Участие'), ('PRIZE', 'Призёр'), ('WINNER', 'Победитель')], default='PARTICIPANT', max_length=20, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='has_certificate',
            field=models.BooleanField(default=False, help_text='Отметьте, если есть сертификат или диплом', verbose_name='Есть сертификат/диплом'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='hours_count',
            field=models.PositiveIntegerField(blank=True, help_text='Для волонтёрства укажите количество часов', null=True, verbose_name='Количество часов'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='level_category',
            field=models.CharField(default=django.utils.timezone.now, help_text='Выберите уровень в зависимости от типа достижения', max_length=30, verbose_name='Уровень/Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='organization',
            field=models.CharField(blank=True, max_length=255, verbose_name='Организация/Учреждение'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='event_type',
            field=models.CharField(choices=[('OLYMPIAD', '🧠 Олимпиада'), ('HACKATHON', '💻 Проект / Хакатон'), ('COURSE', '📚 Курс / Обучение'), ('VOLUNTEERING', '🤝 Волонтерство'), ('SCIENCE', '🔬 Научная работа'), ('SPORT_ART', '🏅 Спорт / Творчество')], max_length=20, verbose_name='Тип достижения'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы за достижение (XP)'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='skills.skill', verbose_name='Подтверждаемые навыки'),
        ),
    ]
