# Generated by Django 6.0.3 on 2026-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт (XP)'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень навыка'),
        ),
    ]
