# Generated by Django 6.0.3 on 2026-03-23 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VOLUNTEERING', 'Волонтерство'), ('HACKATHON', 'Хакатон'), ('COURSE', 'Пройденный курс'), ('OLYMPIAD', 'Олимпиада'), ('PUBLICATION', 'Научная публикация'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип мероприятия')),
                ('title', models.CharField(max_length=255, verbose_name='Название достижения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('proof_link', models.URLField(verbose_name='Ссылка на подтверждение (сертификат/пост)')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Баллы за достижение')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING', 'На проверке'), ('VERIFIED', 'Подтверждено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=10, verbose_name='Статус верификации')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время подтверждения')),
                ('skills', models.ManyToManyField(related_name='achievements', to='skills.skill', verbose_name='Подтверждаемые навыки')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_achievements', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий (Куратор)')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('skills', models.ManyToManyField(to='skills.skill', verbose_name='Прокачиваемые навыки')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
