# Generated by Django 6.0.3 on 2026-03-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название достижения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('proof_link', models.URLField(verbose_name='Ссылка на подтверждение (сертификат/пост)')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Баллы за достижение')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING', 'На проверке'), ('VERIFIED', 'Подтверждено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=10, verbose_name='Статус верификации')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
    ]
