# Generated by Django 6.0.3 on 2026-03-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='skills',
            field=models.ManyToManyField(related_name='achievements', to='skills.skill', verbose_name='Подтверждаемые навыки'),
        ),
    ]
