# Generated by Django 6.0.3 on 2026-03-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время подтверждения'),
        ),
    ]
