# Generated by Django 6.0.3 on 2026-03-27 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_achievement_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название бейджа')),
                ('description', models.TextField(verbose_name='Описание (за что дается)')),
                ('icon', models.ImageField(upload_to='badges/', verbose_name='Иконка бейджа')),
            ],
            options={
                'verbose_name': 'Бейдж',
                'verbose_name_plural': 'Бейджи',
            },
        ),
        migrations.AlterField(
            model_name='achievement',
            name='event_type',
            field=models.CharField(choices=[('VOLUNTEERING', 'Волонтерство'), ('HACKATHON', 'Хакатон'), ('COURSE', 'Пройденный курс'), ('OLYMPIAD', 'Олимпиада'), ('PUBLICATION', 'Научная публикация'), ('TEAM_PROJECT', 'Командный проект'), ('MENTORSHIP', 'Наставничество'), ('OTHER', 'Другое')], default='HACKATHON', max_length=20, verbose_name='Тип мероприятия'),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.badge', verbose_name='Бейдж')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Бейдж пользователя',
                'verbose_name_plural': 'Бейджи пользователей',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
